baseURL: "https://alexloitzl.github.io/"
title: Alex Loitzl 
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: publications/
          weight: 10
        - name: Projects
          url: projects/
          weight: 20
        - name: Posts
          url: blog/
          weight: 40
        - name: Bits
          url: bits/
          weight: 50

params:
    description: "This is Alex Loitzl's personal website hosting research papers, curriculum vitae, and contact information."
    author: Alex Loitzl
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January, 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["publications","projects","posts"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Alex Loitzl
          subtitle: "I'm a PhD student in <a href='https://pub.ista.ac.at/~msammler/'> Michael Sammler's</a> <a href='https://ista.ac.at/en/research/sammler-group/'> Programming Languages and Verification Group </a> at the <a href='https://ista.ac.at'> Institute of Science and Technology Austria</a>. My interests are in the modeling and verification of complex systems, ideally realistic ones. At the moment I am working with <a href='https://plv.mpi-sws.org/dimsum/'>DimSum</a>, an Iris framework for multi-language reasoning. Previously, I was contributing to the (industrial) version of CompCert at <a href='https://www.absint.com'>AbsInt</a> in Saarbr√ºcken."
          imageUrl: "me.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Publications
              url: publications/
            - name: Projects
              url: projects/
            - name: Posts
              url: blog/
            - name: Bits
              url: bits/
    # I will split social icons visually, with more casual ones after a | to be defined in funIcons
    socialIcons:
        - name: Email
          url: "https://www.example.com"
        - name: GitHub
          url: https://github.com/alexloitzl
        - name: LinkedIn
          url: https://www.linkedin.com/in/alexander-loitzl
        # Email is custom to prevent scraping - It's overridden in layouts/partials/social_icons.html
        - name: CV
          url: cv.pdf
    funIcons:
        - name: Discogs
          url: https://www.discogs.com/user/lexiboiiii
        - name: Bandcamp
          url: https://bandcamp.com/lexiboiii

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Alex Loitzl"
      icon: u1f424.svg
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
